from sql_insert import SQL

def dict_from_txt_data(txtfilepath):
    """Converts the text file into a dictionary. Only works on Finish Codes .txt file generated by this project"""
    data_dict = {}
    with open(txtfilepath, "r") as file:
        lines = file.readlines()
        key = lines[4].split()[0]  # need to initialise the first key to ensure that proper parsing happens
        description = ""  # we will keep adding on and then reset once we hit another F or *
        for line in lines[5:]:
            if line.startswith("F-"):
                data_dict[key] = description  # appending to the dict
                description = ""  # erase the value and start over
                key = line.split()[0]  # new key value
            else:
                description += line
    return data_dict

def dict_to_values_list(data_dict: dict, pk: int, filename="D6-5000 REV BV.pdf"):
    """assigns all the values to a list that"""
    values_list = []  # return list
    for key, value in data_dict.items():
            PartNumber = key
            Description = key + " PER " + filename.split(".")[0]
            Revision = filename.split(" ")[2].split(".")[0]
            CanNotInvoice = 1
            CanNotCreateWorkOrder = 1
            DrawingNumber = filename.split(".")[0]
            Comment = value
            PurchaseOrderComment = value
            VendorRevision = 1
            DrawingRevision = 1
            # under manufacturing - stays constant
            ProductDaysExploded = 5
            ExpectReleaseDays = 5
            Days_out = 5
            Po_comments = Comment
            ServiceItem = 1
            purchase = 1
            ForecastOnMRP = 1
            CertificationsRequiredBySupplier = 1
            ShipLoose = 0
            BulkShip = 0
            CalculationTypeFK = 2
            TheManufacturerFK = 2151
            # item pk is mandatory, unique int value
            ItemPK = pk
            pk += 2
            ItemInventoryFK = pk
            pk += 1
            ItemTypeFK = 5
            # still need to find the backend columns for these
            # Revision_number, Days_out, Po_comments
            values = (ItemPK, ItemInventoryFK, PartNumber, Description, Revision, CanNotInvoice, CanNotCreateWorkOrder, DrawingNumber, Comment, PurchaseOrderComment, 
                      ProductDaysExploded, ServiceItem, purchase, VendorRevision, DrawingRevision, ExpectReleaseDays,
                      ForecastOnMRP,  CertificationsRequiredBySupplier, ShipLoose, BulkShip, CalculationTypeFK, TheManufacturerFK, ItemTypeFK)
            values_list.append(values)
    return values_list

main_command = '''INSERT INTO item 
(ItemPK, ItemInventoryFK, PartNumber, Description, Revision, CanNotInvoice, CanNotCreateWorkOrder, DrawingNumber, Comment, PurchaseOrderComment,
ProductDaysExploded, ServiceItem, purchase, VendorRevision, DrawingRevision, ExpectReleaseDays, 
ForecastOnMRP, CertificationsRequiredBySupplier, ShipLoose, BulkShip, CalculationTypeFK, TheManufacturerFK, ItemTypeFK) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'''

if __name__ == "__main__":
    data = dict_from_txt_data("Final.txt")
    values = dict_to_values_list(data, 100000)
    connection = SQL(use_live=True)
    connection.insert_item_inventory(values)
    connection.insert_multiple_values(main_command, values)
